export const Sabores: any = {
   VAINILLAGOURMET: 'VAINILLA GOURMET',
   COCOBLUE: 'COCO BLUE',
   CHOCOLATEGOURMET: 'CHOCOLATE GOURMET',
   VAINILLABLUE: 'VAINILLA BLUE',
   STAWBERRYFUSION: 'STAWBERRY FUSION',
   CITRUSPUNCH: 'CITRUS PUNCH',
   WATERMELON: 'WATERMELON',
   FRUITPUNCH: 'FRUIT PUNCH',
   VAINILLABLANC: 'VAINILLA BLANC',
   BERRIES: 'BERRIES',
   LEMONPIE: 'LEMON PIE',
   GREENMIX: 'GREEN MIX',
   GRAPE: 'GRAPE',
   LEMON: 'LEMON',
   ORANGE: 'ORANGE'
};


